# =============================================================================
# Release pipeline (chart-lib — JS-only npm/git package)
#
# Requires:
#   git  — version control, tagging, push
#   node — JavaScript runtime for Rollup / tsc
#   npm  — package manager + build/test/lint scripts
#   jq   — JSON manipulation for package.json / package-lock.json
#   gh   — GitHub CLI for creating the release
#
# chart-lib ships no PHP, no composer vendor bundle and no distribution zip:
# it is consumed as a git dependency (`github:magicsunday/webtrees-chart-lib#X.Y.Z`),
# so the built `dist/` is committed and the release is just verify → bump →
# commit → tag → push → GitHub release. There is no post-release `-dev` bump;
# package.json stays at the released version until the next release.
#
# Run in an environment that has the JS toolchain directly (e.g. the webtrees
# buildbox). Non-interactive:
#   export GH_TOKEN=<token>
#   make release 1.10.0 NOTES_FILE=/tmp/notes.md
#   make release VERSION=1.10.0 NOTES_FILE=/tmp/notes.md   (also supported)
# =============================================================================

#### Release

# Accept both 'make release 1.10.0' (goal form) and 'make release VERSION=1.10.0'.
VERSION ?= $(filter-out release release-%,$(MAKECMDGOALS))

REQUIRED_TOOLS := git node npm jq gh

.PHONY: release release-check release-prepare release-publish

# In-place jq edit with post-write assertion. Usage:
#   $(call jq_edit,FILE,JQ_FILTER,JQ_ARGS,ASSERT_FILTER)
define jq_edit
( jq --indent 4 $(3) '$(2)' $(1) > $(1).tmp && mv $(1).tmp $(1) ) || ( rm -f $(1).tmp; exit 1 ); \
jq -e $(3) '$(4)' $(1) >/dev/null || { echo "Error: $(1) write did not match $(4)"; exit 1; }
endef

## Validate tools, version, working tree and GitHub auth before any mutation.
release-check:
	@missing=""; \
	for tool in $(REQUIRED_TOOLS); do \
		command -v $$tool >/dev/null 2>&1 || missing="$$missing $$tool"; \
	done; \
	if [ -n "$$missing" ]; then \
		echo "Error: missing required tools:$$missing"; \
		echo "This command requires: $(REQUIRED_TOOLS)"; \
		exit 1; \
	fi
	@if [ -z "$(VERSION)" ]; then \
		echo "Error: VERSION required."; \
		echo "Usage:  make release 1.10.0"; \
		echo "   or:  make release VERSION=1.10.0"; \
		exit 1; \
	fi
	@if ! echo "$(VERSION)" | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+$$'; then \
		echo "Error: VERSION must be bare semver (e.g. 1.10.0 — no v prefix, no suffix)"; \
		exit 1; \
	fi
	@if [ -n "$$(git status --porcelain --untracked-files=no)" ]; then \
		echo "Error: Working directory not clean. Commit or stash changes first."; \
		echo "If a previous release attempt left an unpushed release commit:"; \
		echo "  git tag -d <VERSION>       # if the tag was created"; \
		echo "  git reset --soft HEAD~1    # undo the release commit"; \
		exit 1; \
	fi
	@if ! git symbolic-ref --quiet HEAD >/dev/null 2>&1; then \
		echo "Error: HEAD is detached. Check out the release branch first (typically 'main')."; \
		exit 1; \
	fi
	@if ! gh auth status >/dev/null 2>&1; then \
		echo "Error: Not authenticated with GitHub."; \
		echo "Run 'gh auth login' (interactive) or export GH_TOKEN=<token>."; \
		exit 1; \
	fi
	@echo " ✔ Release checks passed for $(VERSION)"

## Verify (same checks the CI gates: lint + test + build), bump versions,
## rebuild dist, commit "Release X.Y.Z" and tag.
release-prepare: release-check
	@echo "[1/4] Verifying — lint, test, build (CI parity)..."
	@npm ci
	@npm run lint
	@npm test
	@npm run build
	@echo "[2/4] Bumping version to $(VERSION)..."
	@$(call jq_edit,package.json,.version = $$v,--arg v "$(VERSION)",.version == $$v)
	@$(call jq_edit,package-lock.json,(.version = $$v) | (.packages[""].version = $$v),--arg v "$(VERSION)",.version == $$v)
	@echo "[3/4] Committing release commit..."
	@git add package.json package-lock.json dist
	@git commit -m "Release $(VERSION)"
	@echo "[4/4] Tagging $(VERSION)..."
	@git tag $(VERSION)
	@echo " ✔ Release $(VERSION) prepared"

## Push main + tag and create the GitHub release. Notes precedence:
## NOTES_FILE (curated file) > NOTES (inline string) > GitHub auto-generated.
release-publish:
	@if [ -n "$(NOTES_FILE)" ] && [ ! -f "$(NOTES_FILE)" ]; then \
		echo "Error: NOTES_FILE=$(NOTES_FILE) does not exist"; \
		exit 1; \
	fi
	@echo "[publish] Pushing to GitHub..."
	@git push origin main --tags
	@notes_tmp=$$(mktemp); \
	if [ -n "$(NOTES_FILE)" ]; then \
		echo "  Notes: from file $(NOTES_FILE)"; \
		cat "$(NOTES_FILE)" >> "$$notes_tmp"; \
	elif [ -n "$(NOTES)" ]; then \
		echo "  Notes: inline"; \
		printf '%s\n' "$(NOTES)" >> "$$notes_tmp"; \
	else \
		echo "  Notes: auto-generated by GitHub"; \
		repo=$$(gh repo view --json nameWithOwner --jq '.nameWithOwner'); \
		gh api -X POST "repos/$$repo/releases/generate-notes" \
			-f tag_name=$(VERSION) \
			-f target_commitish=main \
			--jq '.body' >> "$$notes_tmp"; \
	fi; \
	gh release create $(VERSION) \
		--title "$(VERSION)" \
		--notes-file "$$notes_tmp"; \
	rm -f "$$notes_tmp"
	@echo " ✔ Release $(VERSION) published"

## Full release: verify → bump → commit → tag → push → GitHub release.
## Usage: make release X.Y.Z [NOTES_FILE=path | NOTES="..."]
release: release-prepare release-publish
	@echo " ✔ Release $(VERSION) complete!"
